---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-cluster
  region: sa-east-1
  version: "1.21"
availabilityZones:
- sa-east-1a
- sa-east-1b
managedNodeGroups:
- name: general
  labels:
    role: general
  instanceType: t3.small
  minSize: 1
  maxSize: 10
  desiredCapacity: 1
  volumeSize: 20
