<<<<<<< HEAD
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::589696708747:role/api-token-access
=======
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
  namespace: production
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::589696708747:role/api-token-access

>>>>>>> 4caf68495ff2960e03a90990694cba8f18906b8d
